### PR TITLE
Default to YAML format for drush make files.

### PR DESCRIPTION
**Pull request by jhedstrom**
Because YAML!

Note, this is dependent on [this drush bug being merged and backported](https://github.com/drush-ops/drush/pull/1386) since we have `====` in our sample .make file, and this gets interpreted as .ini :)

### CODE REVIEW

**Comment by arithmetric** [comment]
@grayside @EvanLovely Any objections to switching to YAML Drush make files by default? The drush bug mentioned looks to be resolved, and I think the format is cleaner and worth adopting moving forward.

**Comment by febbraro** [comment]
Let's do it.

**Comment by smerrill** [comment]
:+1:

**Comment by grayside** [comment]
Yes, this is fine with me. It works because we are bundling drush and do not have a dependency on an old global drush a given environment might have.

**Comment by EvanLovely** [comment]
I'm down!

**Comment by arithmetric** [comment]
@jhedstrom I'd like to see this change in Gadget. Could you resolve the merge conflicts and update the other Drush makefiles that are now part of the repo?

**Comment by jhedstrom** [comment]
@arithmetric done and done. Quite a bit more work this time around than when it was first opened :)

I've manually tested with D7, D8, and OA.

**Comment by arithmetric** [comment]
@jhedstrom Thank you!

I think the tests are failing due to the file name change, and just need an update here: https://github.com/phase2/generator-gadget/blob/master/test/generator.int.test.js#L26

**Comment by jhedstrom** [comment]
@arithmetric tests fixed!

**Comment by arithmetric** [comment]
Yes! :+1: :fireworks:

**Pull request merged**
